"""Utility functions and helpers for ArenaAgent."""

from arenaagent.utils.logger import setup_logger, get_logger, set_log_level
from arenaagent.utils.formatters import (
    format_message,
    format_execution_result,
    format_code,
    format_timestamp,
    create_table,
    format_file_size,
    format_duration,
    format_list,
    truncate_text,
    format_progress,
    format_key_value,
    format_error,
)
from arenaagent.utils.validators import (
    validate_path,
    validate_url,
    is_safe_command,
    validate_json_structure,
    validate_session_id,
    validate_log_level,
    validate_port,
    validate_timeout,
    validate_retry_count,
    sanitize_filename,
    validate_code_language,
)
from arenaagent.utils.file_helpers import (
    atomic_write,
    safe_delete,
    ensure_directory,
    get_file_size,
    copy_with_backup,
    read_file_safe,
    write_file_safe,
    list_files,
    get_file_info,
    create_backup,
    clean_old_backups,
    is_empty_directory,
    get_unique_filename,
)

__all__ = [
    # Logger
    "setup_logger",
    "get_logger",
    "set_log_level",
    # Formatters
    "format_message",
    "format_execution_result",
    "format_code",
    "format_timestamp",
    "create_table",
    "format_file_size",
    "format_duration",
    "format_list",
    "truncate_text",
    "format_progress",
    "format_key_value",
    "format_error",
    # Validators
    "validate_path",
    "validate_url",
    "is_safe_command",
    "validate_json_structure",
    "validate_session_id",
    "validate_log_level",
    "validate_port",
    "validate_timeout",
    "validate_retry_count",
    "sanitize_filename",
    "validate_code_language",
    # File Helpers
    "atomic_write",
    "safe_delete",
    "ensure_directory",
    "get_file_size",
    "copy_with_backup",
    "read_file_safe",
    "write_file_safe",
    "list_files",
    "get_file_info",
    "create_backup",
    "clean_old_backups",
    "is_empty_directory",
    "get_unique_filename",
]
